name: tencent_trtc_cloud_beauty
description: Tencent Real-Time Communication
version: 1.1.1
repository: https://github.com/tencentyun/TRTCFlutterBeautyDemo
homepage: https://cloud.tencent.com/document/product/647

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.2
  dio: ^4.0.0
  archive: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.tencent.trtcplugin
        pluginClass: TRTCCloudPlugin
      ios:
        pluginClass: TencentTRTCCloudBeauty
